[package]
name = "html5ever_nif"
version = "0.1.0"
authors = ["HansiHE <hansihe@hansihe.com>"]

[lib]
name = "html5ever_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[build-dependencies]
rustler_codegen = "^0.12"

[dependencies]
rustler = "^0.12"
rustler_codegen = "^0.12"

html5ever = "*"
tendril = "*"
lazy_static = "*"
scoped-pool = "*"
